---
# This workflow use pytest:
#  - Install Python dependencies.
#  - Run pytest for each of the supported Python versions ["3.8", "3.9", "3.10"]. 
# Running pytest with -m "no docker" to disable test that require a docker installation.

name: Pytest.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
      
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Metasploit.
        run: |
          sudo apt update
          sudo apt install curl gpg
          curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall
          chmod +x msfinstall
          sudo ./msfinstall
          msfrpcd -P Ostorlab123 -p 55552
      - name: Install dependencies.
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e tools/pymetasploit3
          python -m pip install -r requirement.txt
          python -m pip install -r tests/test-requirement.txt
      - name: Running tests with pytest.
        run: |
          set -o pipefail
          pytest -m "not docker" tests/
